import { dashboard } from "./dashboard";
import { login } from "./login";
import {
  newRequisition,
  requisitionsTable,
  requisitionModal,
  requisitionTableHeader,
  requisitionSelectedProductsContent,
  editRequisition,
  showRequisition,
  assignRequisition,
  requisitionStatus,
} from "./requisition";
import {
  newProduct,
  editProduct,
  showProduct,
  productsTable,
  productModal,
  productTableHeader,
} from "./product";
import {
  newStock,
  damagedStock,
  stocksTable,
  stockModal,
  stockReportTableHeader,
  stockTableHeader,
  selectedProductsContent,
  editStock,
  showStock,
  stockFilter,
} from "./stock";
import {
  newPurchase,
  editPurchase,
  showPurchase,
  purchasesTable,
  purchaseModal,
  purchaseTableHeader,
} from "./purchase";
import { buttonText } from "./modal";
import { tableText, paginationText } from "./table";
import { convertedNumber, buttons } from "./global";

export {
  convertedNumber,
  buttons,
  buttonText,
  tableText,
  paginationText,
  login,
  dashboard,
  newRequisition,
  requisitionsTable,
  requisitionModal,
  requisitionTableHeader,
  requisitionSelectedProductsContent,
  editRequisition,
  showRequisition,
  assignRequisition,
  requisitionStatus,
  newProduct,
  editProduct,
  showProduct,
  productsTable,
  productModal,
  productTableHeader,
  damagedStock,
  newStock,
  stocksTable,
  stockModal,
  stockReportTableHeader,
  stockTableHeader,
  selectedProductsContent,
  editStock,
  showStock,
  stockFilter,
  newPurchase,
  editPurchase,
  showPurchase,
  purchasesTable,
  purchaseModal,
  purchaseTableHeader,
};
